### ISSUE TITLE
Update @types/post-load-config

### ISSUE THREAD

**Issue by chang-ke** [postcss/postcss-load-config#210]
Now post-load-config depends on post-css@8.0 but @types/post-load-config depends on post-css@7.0，it's not compatible

**Comment by ai** [comment]
You need send PR to https://github.com/DefinitelyTyped/DefinitelyTyped/

Another option is to move types to `post-load-config`, but it should PR as well

**Comment by chang-ke** [comment]
> You need send PR to https://github.com/DefinitelyTyped/DefinitelyTyped/
> 
> Another option is to move types to `post-load-config`, but it should PR as well

all right. can i use typescript to rewrite it?

**Comment by ai** [comment]
Nope. It will make maintenance more complicated (extra build step, etc).

Just add `.d.ts` file to current `.js` files.
