### ISSUE TITLE
Module resolution issues when root != cwd (vite)

### ISSUE THREAD

**Issue by hpx7** [postcss/postcss-load-config#228]
See https://github.com/vitejs/vite/issues/6386, https://github.com/vitejs/vite/issues/4000

**Comment by ai** [comment]
@hpx7 Can I ask you to send PR with a solution draft?

**Comment by hpx7** [comment]
I don't have a good enough understanding of the underlying issue, I only observed the symptoms.

If you or someone else knows what the culprit is and what would be needed to fix it I can try implementing that.

**Comment by ai** [comment]
The fix was releases in 3.1.2
