### ISSUE TITLE
Move tests from Jest to uvu

### ISSUE THREAD

**Issue by ai** [postcss/postcss-load-config#235]
[`uvu`](https://github.com/lukeed/uvu) is faster and has less bugs with ESM.

We can use `tsm` and `c8` to run TS and code coverage.

Examples:
1. https://github.com/postcss/postcss
2. https://github.com/ai/boilerplates/tree/main/esm-lib

**Comment by usmanyunusov** [comment]
PR - https://github.com/postcss/postcss-load-config/pull/236
