### ISSUE TITLE
missing peer ts-node@>=9.0.0

### ISSUE THREAD

**Issue by ZiiMakc** [postcss/postcss-load-config#241]
pnpm reports following errors when installing postcss/tailwindcss 
```
├─┬ postcss-cli 10.0.0
│ └─┬ postcss-load-config 4.0.1
│   └── ✕ missing peer ts-node@>=9.0.0
└─┬ tailwindcss 3.2.3
  └─┬ postcss-load-config 3.1.4
    └── ✕ missing peer ts-node@>=9.0.0
```

**Comment by ai** [comment]
This dependency marked as optional https://github.com/postcss/postcss-load-config/blob/main/package.json#L52

Do you have any idea why `pnpm` doesn’t see it?

**Comment by ZiiMakc** [comment]
Seems like a pnpm issue: https://github.com/pnpm/pnpm/issues/5152
